services:
  - docker

before_install:
  - docker-compose pull
  - admin.sh pull
  - docker-compose up
  - admin.sh mysql
  - admin.sh makedbuser
  - admin.sh makedb

language: python

script: 
  - admin.sh test
