services:
  - docker

before_install:
  - docker-compose pull
  - ./admin.sh pull
  - ./admin.sh mysql
  - ./admin.sh makedbuser
  - ./admin.sh makedb
  - docker-compose up

language: python

script: 
  - admin.sh test
