services:
  - docker

before_install:
  - docker-compose pull
  - ./admin.sh pull
  - ./admin.sh mysql
  - docker-compose up
  - ./admin.sh makedbuser
  - ./admin.sh makedb

language: python

script: 
  - admin.sh test
