services:
  - docker

before_install:
  - docker-compose pull
  - docker pull mysql:5.7.23
  - ./admin.sh pull
  - ./admin.sh newdb
  - docker-compose up

language: python

script: 
  - ./admin.sh test
  - ./admin.sh seleniumtest
