models:
  image: tp33/django
  external_links:
    - mysql:db
  volumes:
    - ./app:/app
  ports:
    - "8001:8000"
  command: bash -c "mod_wsgi-express start-server --working-directory /app/partex/partex --reload-on-changes app/partex/partex/wsgi.py"
