# vim: et:ts=2:sw=2

version: '3'

services:
  kafka:
    image: spotify/kafka
    container_name: kafka
    network_mode: default
    environment:
       ADVERTISED_HOST: kafka
       ADVERTISED_PORT: 9092
    hostname: kafka

  es:
    image: elasticsearch:2.0
    container_name: es
    network_mode: default
    ports:
      - "9200:9200"

  batch:
    image: tp33/django
    container_name: batch
    network_mode: default
    volumes:
      - ./batch:/batch
    links:
      - kafka:kafka
      - es:es
    command: python /batch/kafka_to_es.py

  models:
    image: tp33/django
    container_name: models
    network_mode: default
    external_links:
      - mysql:db
    volumes:
      - ./app-models:/app
    ports:
      - "8002:8000"
    command:
      # bash -c "/usr/bin/env python3 /app/manage.py runserver 0.0.0.0:8000"
      bash -c "python /app/manage.py migrate &&
      python /app/manage.py loaddata /app/partex/db/fixtures/users.json &&
      python /app/manage.py loaddata /app/partex/db/fixtures/listings.json &&
      python /app/manage.py loaddata /app/partex/db/fixtures/reviews.json &&
      mod_wsgi-express start-server --reload-on-changes /app/partex/wsgi.py &&
      python /app/manage.py initindex"
      # /usr/bin/env python3 /app/manage.py runserver 0.0.0.0:8000"

  exp:
    image: tp33/django
    container_name: exp
    network_mode: default
    volumes:
      - ./app-experience:/app
    ports:
      - "8001:8000"
    links:
      - models:models
      - es:es
      - kafka:kafka
    command:
      "mod_wsgi-express start-server /app/partex/wsgi.py"
      # "/usr/bin/env python3 /app/manage.py runserver 0.0.0.0:8000"

  web:
    build: app-web/
    container_name: web
    network_mode: default
    volumes:
      - ./app-web:/app
    ports:
      - "8000:8000"
    links:
      - exp:partex-experience
      - redis:redis
    command:
      "mod_wsgi-express start-server /app/partex/wsgi.py"
      # "/usr/bin/env python3 /app/manage.py runserver 0.0.0.0:8000"

  selenium-chrome:
    image: selenium/standalone-chrome
    container_name: selenium-chrome
    network_mode: default
    links:
      - web:web
    ports:
      - "4444:4444"

  selenium-test:
    image: tp33/django
    container_name: selenium-test
    network_mode: default
    links:
      - selenium-chrome:selenium-chrome
      - web:web
    volumes:
      - ./selenium:/selenium
    command: bash -c "pip install selenium==3.10.0 && python /selenium/web_testing.py"

  lb:
    build: lb
    container_name: haproxy
    network_mode: default
    ports:
      - "8888:80"
    links:
      - web:web

  redis:
    image: redis
    container_name: redis
    network_mode: default
    ports:
      - "6379:6379"

  spark-master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    container_name: spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./spark-data:/tmp/data

  spark-worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    container_name: spark-worker
    hostname: spark-worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 512m
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    links:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./spark-data:/tmp/data

  spark-batch:
    image: tp33/django
    container_name: spark-batch
    network_mode: default
    volumes:
      - ./spark-data:/app
    links:
      - kafka:kafka
    command: python /app/spark_kafka.py
